version: "3"

services:
  tg_bot:
    build: tg_bot/
    restart: always
    environment:
      - TG_TOKEN=${TG_TOKEN} # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных

  vk_bot:
    build: vk_bot/
    restart: always
    environment:
      - VK=${VK_TOKEN} # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных

  notification_service:
    build: notification_service/
    restart: always
    environment:
      - TG_TOKEN=${TG_TOKEN} # токен telegram бота
      - VK_TOKEN=${VK_TOKEN} # токен VK бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных

  getting_schedule:
    build: getting_schedule/
    restart: always
    environment:
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB (default: 27017)
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных MongoDB (default: Smart_schedule_IRNITU)
      - PG_DB_DATABASE=${PG_DB_DATABASE} # название базы данных PostgreSQL (default: schedule)
      - PG_DB_USER=${PG_DB_USER} # пользователь PostgreSQL
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}  # пароль PostgreSQL
      - PG_DB_HOST=${PG_DB_HOST} # адрес PostgreSQL
      - PG_DB_PORT=5432 # порт PostgreSQL (default: 5432)
      - GETTING_SCHEDULE_TIME_HOURS=1 # время задержки (в часах) между обращениями к PostgreSQL для получения расписания (default: 1)

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    restart: always
